# 这个应用必须发布在根路径下
server:
  servlet:
    context-path: "/"
  port: 1986
mock:
  http:
    config:
      mock:
        location: "classpath:HttpMockConfig.json"
      forward:
        location: "classpath:HttpForwardConfig.json"
      record:
        location: "classpath:config"