# 这个应用必须发布在根路径下
server:
  servlet:
    context-path: "/"
  port: 1986
mock:
  http:
    config:
      mock:
        location: "/Users/linjun/git/mock/src/main/resources/HttpForwardConfig.json"
      forward:
        location: "/Users/linjun/git/mock/src/main/resources/HttpMockConfig.json"
      record:
        location: "/Users/linjun/git/mock/src/main/resources/config"