# 这个应用必须发布在根路径下
server:
  servlet:
    context-path: "/"
  port: 1986
mock:
  http:
    config:
      mock:
        location: "E:\\git\\mock\\src\\main\\resources\\HttpMockConfig.json"
      forward:
        location: "E:\\git\\mock\\src\\main\\resources\\HttpForwardConfig.json"
      record:
        location: "E:\\git\\mock\\src\\main\\resources\\"